version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 1
    rebase-strategy: 'auto'
    labels:
      - 'dependencies'
    assignees:
      - 'demns'
    reviewers:
      - 'demns'
    milestone: 1
